# ----------------------------
# Makefile Options
# ----------------------------

NAME = CASINO_A
ICON = icon.png
DESCRIPTION = "Automatic casino simulator"
COMPRESSED = YES
ARCHIVED = YES
HAS_PRINTF = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
