# ----------------------------
# Makefile Options
# ----------------------------

NAME = CASINO_U
ICON = icon.png
DESCRIPTION = "User powered casino simulator"
COMPRESSED = YES
ARCHIVED = YES
HAS_PRINTF = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
